[tool.poetry]
name = "python-tests"
version = "0.1.0"
description = "BMAT Test"
authors = ["lermanDev <info@lerman.es>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
